### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Arkosen** [abl0719/ASElux#1]
Hi I was extremely interested in running ASElux however I am running into a memory issue
I am running it on a cluster and it keeps giving me the following error:
loading index: /iblm/netapp/home/asen/Genomes/Homo_sapiens/UCSC/hg19/Sequence/ASElux_index/ASElux_index
Building dynamic index...
Segmentation fault (core dumped)
 the demo files run fine

**Comment by abl0719** [comment]
Hi, could you please provide the detailed parameter you used for this run?

**Comment by tojojames** [comment]
When I try to build static index, it fails with error -- "Segmentation fault (core dumped)"

./ASElux build --gtf annotation_100.gtf --ref hg19_chr1.fa --out test
Building static index...
Segmentation fault (core dumped)

It works fine with the demo dataset and with the small gtf file (of 100 lines).Any quick advise/fix will be helpful.Thanks!

**Comment by abl0719** [comment]
Issue closed due to no response.

**Comment by inti** [comment]
Hi,
I am having the same issue. the is the command line I am using 
```
bin/ASElux build --gtf Bombus_terrestris.Bter_1.0.39.gtf --ref Bombus_terrestris.Bter_1.0.dna.toplevel.fa --out test_aselux
```
and 
```
intipedroso$ ../app/ASElux/bin/ASElux align --fq --pe --readLen 90 --index ../ref_genomes/Bombus_terrestris/test_aselux --seqFiles fastq/SRR5125102_1.fastq.gz fastq/SRR5125102_2.fastq.gz --vcf  vcf/genotype_call_imputed.vcf --gtf ../ref_genomes/Bombus_terrestris/gtf/Bombus_terrestris.Bter_1.0.39.gtf --ref ../ref_genomes/Bombus_terrestris.Bter_1.0.dna.toplevel.fa --nthread 1 --out test --count_once
loading index: ../ref_genomes/Bombus_terrestris/test_aselux
Building dynamic index... 
Segmentation fault: 11
```

All files with the exception of the vcf are public so that should help to reproduce the error. 
my system is 
```intipedroso$ uname -a
Darwin Deathstalker.local 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64
```
looking forwards to have your help
