### ISSUE TITLE
Error "read reading went wrong.." and no output

### ISSUE THREAD

**Issue by passdan** [abl0719/ASElux#11]
I am receiving the following error but can't determine the issue. The demo dataset works perfectly.

```
loading index: /trinity/home/scratchspace/ASE_mm
Building dynamic index... 
Start alignment... 
read reading went wrong..
read reading went wrong..
read reading went wrong..
read reading went wrong..
read reading went wrong..
[repeat]
```

The input data is fastq.gz  and have been used previously and successfully in STAR analysis. The vcf, gtf, and genome files are all from ensembl and are compatible (i.e. on chromosome names).

I can't determine the cause of the issue and the error message isn't very informative.

Thanks

**Comment by abl0719** [comment]
Hi, currently ASElux does not tak the gz files as input. If you unpack the fastq files into plain text, it should work fine.

**Comment by passdan** [comment]
Thanks for the update
