### ISSUE TITLE
[Suggestion] Segmentation fault caused my using vcf v4.1 (v4.2 required)

### ISSUE THREAD

**Issue by passdan** [abl0719/ASElux#12]
Hi

I had several hours of frustration today trying to find the cause of a "segmentation fault" error. 

It turns out that the issue is the vcf file having 2 few columns (v4.1 standard) and not including GT and the 1/0 columns that are standard in v4.2.

Would it be possible to add a check when reading the file to ensure that the correct version is used and give an informative error (i.e. "Your vcf file has too few columns, make sure you are using a v4.2 format file"). I'm sure that would help many more people in the future.

Thanks

**Comment by abl0719** [comment]
Thank you for the feedback. I've updated the readme file for the notice. A checkpoint in the software will be implemented in the future.
