### ISSUE TITLE
Gene expression level calculation

### ISSUE THREAD

**Issue by Zefeng-Wu** [abl0719/ASElux#13]
Hi, How to obtain the gene expression level (e. g, the total reads number mapped to a gene or FPKM value) besides the allele-specific reads number in the position with SNPs?

**Comment by abl0719** [comment]
Hi, ASElux does not align all reads and therefore can not provide the gene-level expression. You can use other tools such as STAR + featureCounts or Kallisto to obtain gene/transcript level expressions.
