### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by alfonsosaera** [abl0719/ASElux#15]
Hi,

I get this error

`Segmentation fault (core dumped)`

when building an index for hg19 human genome as follows

```ASElux build --gtf Homo_sapiens.GRCh37.87.gtf --ref Homo_sapiens.GRCh37.dna.toplevel.fa --out ASElux.index```

Thanksf for your help!

**Comment by alfonsosaera** [comment]
Using simple names for chromosomes (`>1` instead of `>1 more text here`) did not help. I downloaded fasta file and gff3 from ensembl archive (`ftp://ftp.ensembl.org/pub/grch37/current`) and then generated gtf from the gff3 with `gffread` 

`gffread Homo_sapiens.GRCh37.87.gff3 -T -o Homo_sapiens.GRCh37.87.gtf`

Thanks again for your help

**Comment by abl0719** [comment]
You need Homo_sapiens.GRCh37.dna.primary_assembly.fa instead of Homo_sapiens.GRCh37.dna.toplevel.fa as the reference genome. The current version of ASElux is compatible with extra texts after chromosome names. So there is no need to modify the fasta file for the  ">1 more text here" situation. 

By the way, there is a gtf file available from Ensembl (ftp://ftp.ensembl.org/pub/grch37/current/gtf/homo_sapiens/Homo_sapiens.GRCh37.87.gtf.gz), so It might be better to directly download the gtf file and use that one.

**Comment by alfonsosaera** [comment]
Hi,

Thanks for your answer. I cannot believe I missed the gtf file! 

Following your suggestions:

`ASElux build --gtf Homo_sapiens.GRCh37.87.gtf --ref Homo_sapiens.GRCh37.dna.primary_assembly.fa --out ASElux.index`

 it works with no errors, just a typo:

`Building static index...`
`Anootation finished...`
`annotation created...`

Second line says `Anootation` instead of `Annotation`.

Thanks again for your help!

**Comment by alfonsosaera** [comment]
Hi @abl0719 ,

I got again `Segmentation fault (core dumped)` error when trying to align FASTQ files to the index generated as shown in the previous post.

The command:
`ASElux align --fq --pe --readLen 151 --nthread 1 --index "${index}/ASElux.index" --vcf "${SNP}/S3_1_mutect.snp.X.vcf" --seqFiles M_18_3207_1294_AD012_L006_R1_001.fq M_18_3207_1294_AD012_L006_R2_001.fq --out "${OUTfold}/3207_1294.S3_1.47XXY.txt"`

And the output:
`loading index: /media/sequentia/sharing/genomes/homo_sapiens_ADMIN_May-15-112307-2018_Conflict/hg19_GRCh37/ASElux.index`
`Building dynamic index... `
`Segmentation fault (core dumped)`

**Index** file:
`xxd -b "${index}/ASElux.index.annotation" | head n3`
`00000000: 01100101 10000101 00000000 00000000 00000000 00000000  e.....`
`00000006: 00000000 00000000 00101010 01001011 00000000 00000000  ..*K..`
`0000000c: 00100011 01010001 00000000 00000000 11000100 01011010  #Q...Z`

FASTQ **R1** file:
`head -n12 M_18_3207_1294_AD012_L006_R1_001.fq`
`@K00235:151:HWMYKBBXX:6:1101:1407:1367 1:N:0:CTTGTA
GNTCGACTGGAACCAGAACACAATAAATTTGTCAAGCTCGTTCTTCCACATGCAGCAGGCCTGAGGGCTGCAGTGGCAGAAATGCCCCAAGGAATGGCACTCACATGTCGGGCAACCGACGCTCGGAGCAACCGTCCTACAGCAGCCGCCA`
`+`
`A#AAFFJJJFFFJ<FJJ7FJJJJJJJJJJFJAAFJJJ<FJJFFJJJJJJ-7FJ-7FAJJJJFJ<A-AF-AAJFF-AF-FAFFF7FJJJAFJJJJJJFF---7FJJ7JF<AJFJJFJJJJA7JJJJJ-<FFA<-<JJ<J--7FF-FFJJA<A`
`@K00235:151:HWMYKBBXX:6:1101:1732:1367 1:N:0:CTTGTA
TTCACAAGCAAAGGGATCTGCACTCTTTCTCTGCCCCCACTCAGTTCAAATTTCCATGGATGGCTTCTCATTCCTCACAAGTAAAAACACTTATGGAACATCTTGGAGTTCTAAAGATCGGAAGAGCACACGTCTGAACTCCAGTCACCTT`
`+`
`-AAFFJJJJJFFJFJJJJJJJJJJJJJFJJJF7AAFJAJJ-FJJJAFFFAFJJJ<JAJAJ<JJJF-A<JFJJJJJJ-F7AJJJJ<FJJ-AFFFJJJFJJJJJJJJJJJ<FJ<FAJJAAJ-AFJFJJ<JJJJJFFJJF-7-AFAFAJ-FJ--`
`@K00235:151:HWMYKBBXX:6:1101:1854:1367 1:N:0:CTTGTA
GGAGCAGATTGGGTAATAAAATGTATTTTGAGAATAAGACGGCCTTTTGACCTTTTAGGGTCTAGGGCTGTAAAGCGTCTCAGGGTTGCTGCCAAACAAGTCATGAACTGGGCGGGATTTTTATATTTGATGAAAAAGAGACTAAACGCTT`
`+`
`AAFFFJAJAFJJJAJJFJJJJJJJJFJ<FJFJJAJJJJFJJJFJFJJJFJF<-F7AFJJJ7AFJJ-FAJJJFJA-<777<FAJ7<7FJJJJAFF--A--F7FFFFFFJJFAA--AAAJJF-7-77A-AJFA<AFAJJA---7-AAA-7AFJ`

FASTQ **R2** file:
`head -n12 M_18_3207_1294_AD012_L006_R2_001.fq`
`@K00235:151:HWMYKBBXX:6:1101:1407:1367 2:N:0:CTTGTA
TGAAGATGGCGGCTGCTGTAGGACGGTTGCTCCGAGCGTCGGTTGCCCGACATGTGAGTGCCATTCCTTGGGGCATTTCTGCCACTGCAGCCCTCAGGCCTGCTGCATGTGGAAGAACGAGCTTGACAAATTTATTGTGTTCTGGTTCAAG`
`+`
`<AAAFA<AJJJ-F-FA<JJJJJJJJF<JJJFJFJJJJ<7JJJJJJJJFJJJFAJ7JAA7FA<J-A7AJJFJJJJJ<AFFJJ<AJ-F<FJJJFJFJ-AJJ--<FFJJ7JJJFFJFJJFAFFF<7--<--<AAFF-A---AAJFJAJ<----7`
`@K00235:151:HWMYKBBXX:6:1101:1732:1367 2:N:0:CTTGTA
TTAGAACTCCAAGATGTTCCATAAGTGTTTTTACTTGTGAGGAATGAGAAGCCATCCATGGAAATTTGAACTGAGTGGGGGCAGAGAAAGAGTGCAGATCCCTTTGCTTGTGAAAGATCGGAAGAGCGTTCGTGTAGGGAAAGAGTGTAGA`
`+`
`AAAFFJJJJAFJJJJJJFJJJJJJJJJFJJJJJJ<<FJJJJJFJJJJFAJFJJFAJFJFAJF<FFJ<<FAFJJJJJA<FFJJJJJAAFF7AJJFFFAJJJJ<JJFFJJJ<JFFJJJJ-<F<FFJJJJJJFAJJFAAFJ<-<7AAJF--<<<`
`@K00235:151:HWMYKBBXX:6:1101:1854:1367 2:N:0:CTTGTA
TGCCCAGCAATTTACTCTTAAAAAGGTGGCTGGAGCTAAAGGCATAGTCAAGGTTAATGCTCCTTTTTTTTTTTCCCAAATCAGAAGAGTTTAGGCTCTTTTTCATCAAATATAAAAATCCAGCCCAGTTCATCACTTGTTTGGCAGCACC`
`+`
`AAFFFJJJJJJJJJJJJJJFJJJJF<FJFFFAJJAJJJJJJJJJFJJJJJJJJ-AFAFJJ7JJJJJJJ-FJ--A-A77<AJ<J-7FA--77-7A--<FF-AFJAJA7FA<AAAFAA<J-7<J77A7))A<<---7-7F7-7A--7-))-))`

**VCF** file, as you can see the header is about 150 lines. Please let me know if you need the whole file/header.
`sed -n '1,10p;150,160p' "${SNP}/S3_1_mutect.snp.X.vcf"`
`##fileformat=VCFv4.2`
`##FILTER=<ID=base_qual,Description="alt median base quality">`
`##FILTER=<ID=clustered_events,Description="Clustered events observed in the tumor">`
`##FILTER=<ID=contamination,Description="contamination">`
`##FILTER=<ID=duplicate,Description="evidence for alt allele is overrepresented by apparent duplicates">`
`##FILTER=<ID=fragment,Description="abs(ref - alt) median fragment length">`
`##FILTER=<ID=germline,Description="Evidence indicates this site is germline, not somatic">`
`##FILTER=<ID=haplotype,Description="Variant near filtered variant on same haplotype.">`
`##FILTER=<ID=low_allele_frac,Description="Allele fraction is below specified threshold">`
`##FILTER=<ID=map_qual,Description="ref - alt median mapping quality">`
`...`
`##filtering_status=These calls have been filtered by FilterMutectCalls to label false positives with a list of failed filters and true positives with PASS.`
`##reference=file:///NJPROJ2/HW/PUBLIC/source/Disease/database/genome/human/b37_gatk/human_g1k_v37_decoy.fasta`
`##source=FilterMutectCalls`
`##source=SelectVariants`
`##tumor_sample=S3_1`
`#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	S3_1`
`X	60069	.	T	A	.	PASS	CONTQ=93;DP=1;ECNT=1;GERMQ=45;MBQ=0,37;MFRL=0,0;MMQ=60,60;MPOS=4;POPAF=7.30;SEQQ=14;STRANDQ=38;TLOD=3.87	GT:AD:AF:DP:F1R2:F2R1:SB	0/1:0,1:0.667:1:0,0:0,1:0,0,0,1`
`X	60185	.	T	C	.	PASS	CONTQ=93;DP=2;ECNT=2;GERMQ=39;MBQ=37,37;MFRL=228,0;MMQ=60,60;MPOS=29;POPAF=7.30;SEQQ=6;STRANDQ=34;TLOD=3.40	GT:AD:AF:DP:F1R2:F2R1:SB	0/1:1,1:0.500:2:0,0:1,1:1,0,0,1`
`X	60215	.	A	C	.	PASS	CONTQ=93;DP=3;ECNT=2;GERMQ=39;MBQ=37,37;MFRL=228,262;MMQ=60,60;MPOS=11;POPAF=7.30;SEQQ=5;STRANDQ=35;TLOD=3.35	GT:AD:AF:DP:F1R2:F2R1:SB	0/1:1,1:0.500:2:0,0:1,1:1,0,1,0`
`X	60454	.	A	G	.	PASS	CONTQ=93;DP=1;ECNT=1;GERMQ=45;MBQ=0,37;MFRL=0,262;MMQ=60,60;MPOS=11;POPAF=7.30;SEQQ=14;STRANDQ=38;TLOD=3.88	GT:AD:AF:DP:F1R2:F2R1:SB	0/1:0,1:0.667:1:0,0:0,1:0,0,0,1`
`X	60882	.	T	G	.	PASS	CONTQ=93;DP=2;ECNT=1;GERMQ=39;MBQ=20,37;MFRL=146,203;MMQ=60,60;MPOS=7;POPAF=7.30;SEQQ=6;STRANDQ=35;TLOD=3.40	GT:AD:AF:DP:F1R2:F2R1:SB	0/1:1,1:0.501:2:1,1:0,0:1,0,1,0`

I also confirmed I have permits to write to the output file:

`echo "hi" > "${OUTfold}/3207_1294.S3_1.47XXY.txt" ; cat "${OUTfold}/3207_1294.S3_1.47XXY.txt"`
`hi`

Thanks again for your help!
