### ISSUE TITLE
Segmentation fault (core dumped) with ASElux align

### ISSUE THREAD

**Issue by alfonsosaera** [abl0719/ASElux#16]
Hi @abl0719 ,

I am opening a new issue just in case you did not see my new post in the issue about the core dumped error building the index. 

Thanks again for your help!

ORIGINAL POST:

I got again `Segmentation fault (core dumped)` error when trying to align FASTQ files to the index generated as shown in the previous post.

The command:
`ASElux align --fq --pe --readLen 151 --nthread 1 --index "${index}/ASElux.index" --vcf "${SNP}/S3_1_mutect.snp.X.vcf" --seqFiles M_18_3207_1294_AD012_L006_R1_001.fq M_18_3207_1294_AD012_L006_R2_001.fq --out "${OUTfold}/3207_1294.S3_1.47XXY.txt"`

And the output:
`loading index: /media/sequentia/sharing/genomes/homo_sapiens_ADMIN_May-15-112307-2018_Conflict/hg19_GRCh37/ASElux.index`
`Building dynamic index... `
`Segmentation fault (core dumped)`

**Index** file:
`xxd -b "${index}/ASElux.index.annotation" | head n3`
`00000000: 01100101 10000101 00000000 00000000 00000000 00000000  e.....`
`00000006: 00000000 00000000 00101010 01001011 00000000 00000000  ..*K..`
`0000000c: 00100011 01010001 00000000 00000000 11000100 01011010  #Q...Z`

FASTQ **R1** file:
`head -n12 M_18_3207_1294_AD012_L006_R1_001.fq`
`@K00235:151:HWMYKBBXX:6:1101:1407:1367 1:N:0:CTTGTA
GNTCGACTGGAACCAGAACACAATAAATTTGTCAAGCTCGTTCTTCCACATGCAGCAGGCCTGAGGGCTGCAGTGGCAGAAATGCCCCAAGGAATGGCACTCACATGTCGGGCAACCGACGCTCGGAGCAACCGTCCTACAGCAGCCGCCA`
`+`
`A#AAFFJJJFFFJ<FJJ7FJJJJJJJJJJFJAAFJJJ<FJJFFJJJJJJ-7FJ-7FAJJJJFJ<A-AF-AAJFF-AF-FAFFF7FJJJAFJJJJJJFF---7FJJ7JF<AJFJJFJJJJA7JJJJJ-<FFA<-<JJ<J--7FF-FFJJA<A`
`@K00235:151:HWMYKBBXX:6:1101:1732:1367 1:N:0:CTTGTA
TTCACAAGCAAAGGGATCTGCACTCTTTCTCTGCCCCCACTCAGTTCAAATTTCCATGGATGGCTTCTCATTCCTCACAAGTAAAAACACTTATGGAACATCTTGGAGTTCTAAAGATCGGAAGAGCACACGTCTGAACTCCAGTCACCTT`
`+`
`-AAFFJJJJJFFJFJJJJJJJJJJJJJFJJJF7AAFJAJJ-FJJJAFFFAFJJJ<JAJAJ<JJJF-A<JFJJJJJJ-F7AJJJJ<FJJ-AFFFJJJFJJJJJJJJJJJ<FJ<FAJJAAJ-AFJFJJ<JJJJJFFJJF-7-AFAFAJ-FJ--`
`@K00235:151:HWMYKBBXX:6:1101:1854:1367 1:N:0:CTTGTA
GGAGCAGATTGGGTAATAAAATGTATTTTGAGAATAAGACGGCCTTTTGACCTTTTAGGGTCTAGGGCTGTAAAGCGTCTCAGGGTTGCTGCCAAACAAGTCATGAACTGGGCGGGATTTTTATATTTGATGAAAAAGAGACTAAACGCTT`
`+`
`AAFFFJAJAFJJJAJJFJJJJJJJJFJ<FJFJJAJJJJFJJJFJFJJJFJF<-F7AFJJJ7AFJJ-FAJJJFJA-<777<FAJ7<7FJJJJAFF--A--F7FFFFFFJJFAA--AAAJJF-7-77A-AJFA<AFAJJA---7-AAA-7AFJ`

FASTQ **R2** file:
`head -n12 M_18_3207_1294_AD012_L006_R2_001.fq`
`@K00235:151:HWMYKBBXX:6:1101:1407:1367 2:N:0:CTTGTA
TGAAGATGGCGGCTGCTGTAGGACGGTTGCTCCGAGCGTCGGTTGCCCGACATGTGAGTGCCATTCCTTGGGGCATTTCTGCCACTGCAGCCCTCAGGCCTGCTGCATGTGGAAGAACGAGCTTGACAAATTTATTGTGTTCTGGTTCAAG`
`+`
`<AAAFA<AJJJ-F-FA<JJJJJJJJF<JJJFJFJJJJ<7JJJJJJJJFJJJFAJ7JAA7FA<J-A7AJJFJJJJJ<AFFJJ<AJ-F<FJJJFJFJ-AJJ--<FFJJ7JJJFFJFJJFAFFF<7--<--<AAFF-A---AAJFJAJ<----7`
`@K00235:151:HWMYKBBXX:6:1101:1732:1367 2:N:0:CTTGTA
TTAGAACTCCAAGATGTTCCATAAGTGTTTTTACTTGTGAGGAATGAGAAGCCATCCATGGAAATTTGAACTGAGTGGGGGCAGAGAAAGAGTGCAGATCCCTTTGCTTGTGAAAGATCGGAAGAGCGTTCGTGTAGGGAAAGAGTGTAGA`
`+`
`AAAFFJJJJAFJJJJJJFJJJJJJJJJFJJJJJJ<<FJJJJJFJJJJFAJFJJFAJFJFAJF<FFJ<<FAFJJJJJA<FFJJJJJAAFF7AJJFFFAJJJJ<JJFFJJJ<JFFJJJJ-<F<FFJJJJJJFAJJFAAFJ<-<7AAJF--<<<`
`@K00235:151:HWMYKBBXX:6:1101:1854:1367 2:N:0:CTTGTA
TGCCCAGCAATTTACTCTTAAAAAGGTGGCTGGAGCTAAAGGCATAGTCAAGGTTAATGCTCCTTTTTTTTTTTCCCAAATCAGAAGAGTTTAGGCTCTTTTTCATCAAATATAAAAATCCAGCCCAGTTCATCACTTGTTTGGCAGCACC`
`+`
`AAFFFJJJJJJJJJJJJJJFJJJJF<FJFFFAJJAJJJJJJJJJFJJJJJJJJ-AFAFJJ7JJJJJJJ-FJ--A-A77<AJ<J-7FA--77-7A--<FF-AFJAJA7FA<AAAFAA<J-7<J77A7))A<<---7-7F7-7A--7-))-))`

**VCF** file, as you can see the header is about 150 lines. Please let me know if you need the whole file/header.
`sed -n '1,10p;150,160p' "${SNP}/S3_1_mutect.snp.X.vcf"`
`##fileformat=VCFv4.2`
`##FILTER=<ID=base_qual,Description="alt median base quality">`
`##FILTER=<ID=clustered_events,Description="Clustered events observed in the tumor">`
`##FILTER=<ID=contamination,Description="contamination">`
`##FILTER=<ID=duplicate,Description="evidence for alt allele is overrepresented by apparent duplicates">`
`##FILTER=<ID=fragment,Description="abs(ref - alt) median fragment length">`
`##FILTER=<ID=germline,Description="Evidence indicates this site is germline, not somatic">`
`##FILTER=<ID=haplotype,Description="Variant near filtered variant on same haplotype.">`
`##FILTER=<ID=low_allele_frac,Description="Allele fraction is below specified threshold">`
`##FILTER=<ID=map_qual,Description="ref - alt median mapping quality">`
`...`
`##filtering_status=These calls have been filtered by FilterMutectCalls to label false positives with a list of failed filters and true positives with PASS.`
`##reference=file:///NJPROJ2/HW/PUBLIC/source/Disease/database/genome/human/b37_gatk/human_g1k_v37_decoy.fasta`
`##source=FilterMutectCalls`
`##source=SelectVariants`
`##tumor_sample=S3_1`
`#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	S3_1`
`X	60069	.	T	A	.	PASS	CONTQ=93;DP=1;ECNT=1;GERMQ=45;MBQ=0,37;MFRL=0,0;MMQ=60,60;MPOS=4;POPAF=7.30;SEQQ=14;STRANDQ=38;TLOD=3.87	GT:AD:AF:DP:F1R2:F2R1:SB	0/1:0,1:0.667:1:0,0:0,1:0,0,0,1`
`X	60185	.	T	C	.	PASS	CONTQ=93;DP=2;ECNT=2;GERMQ=39;MBQ=37,37;MFRL=228,0;MMQ=60,60;MPOS=29;POPAF=7.30;SEQQ=6;STRANDQ=34;TLOD=3.40	GT:AD:AF:DP:F1R2:F2R1:SB	0/1:1,1:0.500:2:0,0:1,1:1,0,0,1`
`X	60215	.	A	C	.	PASS	CONTQ=93;DP=3;ECNT=2;GERMQ=39;MBQ=37,37;MFRL=228,262;MMQ=60,60;MPOS=11;POPAF=7.30;SEQQ=5;STRANDQ=35;TLOD=3.35	GT:AD:AF:DP:F1R2:F2R1:SB	0/1:1,1:0.500:2:0,0:1,1:1,0,1,0`
`X	60454	.	A	G	.	PASS	CONTQ=93;DP=1;ECNT=1;GERMQ=45;MBQ=0,37;MFRL=0,262;MMQ=60,60;MPOS=11;POPAF=7.30;SEQQ=14;STRANDQ=38;TLOD=3.88	GT:AD:AF:DP:F1R2:F2R1:SB	0/1:0,1:0.667:1:0,0:0,1:0,0,0,1`
`X	60882	.	T	G	.	PASS	CONTQ=93;DP=2;ECNT=1;GERMQ=39;MBQ=20,37;MFRL=146,203;MMQ=60,60;MPOS=7;POPAF=7.30;SEQQ=6;STRANDQ=35;TLOD=3.40	GT:AD:AF:DP:F1R2:F2R1:SB	0/1:1,1:0.501:2:1,1:0,0:1,0,1,0`

I also confirmed I have permits to write to the output file:

`echo "hi" > "${OUTfold}/3207_1294.S3_1.47XXY.txt" ; cat "${OUTfold}/3207_1294.S3_1.47XXY.txt"`
`hi`

Thanks again for your help!

_Originally posted by @alfonsosaera in https://github.com/abl0719/ASElux/issues/15#issuecomment-565370862_

**Comment by abl0719** [comment]
Hi @alfonsosaera, could you please check if you have any homozygous SNPs (GT=1/1) available in your VCF file? If there is no homozygous SNP, this error might occur.

**Comment by alfonsosaera** [comment]
Hi  @abl0719,

You are absolutly right. The vcf has no homozygous SNPs. Does this mean I cannot use ASElux for my analysis?

Thanks again!

**Comment by abl0719** [comment]
Keeping the homozygous SNP information would help to improve the alignment accuracy. So we highly recommend keeping the homozygous SNPs if possible. However, I'm working on updating the software so that this situation can be handled correctly. The new version should be ready soon.

Can I ask why you are missing all the homozygous SNPs? If it's converted from the PLINK files, please note that PLINK usually does not keep track of the reference allele properly. In that case, the current version of ASElux can not handle the switched genotypes.

**Comment by alfonsosaera** [comment]
Thanks again for your answer. I am running the analysis for someone else and, apparently, the sequencing company made the variant calling and gave them only heterozygous SNPs. I will ask them about this and run ASElux with all SNPs if I can.
