### ISSUE TITLE
README clarification and ASEleux precompiled binary file

### ISSUE THREAD

**Issue by Dazcam** [abl0719/ASElux#17]
Hello,

I'm really interested in using this package but I'm having trouble installing it on our cluster.

Could you confirm the compiler version that is required to install ASElux from source? The README doc has conflicting information. It states that 'it requires a gcc version >= 5', and then a few lines later is says it 'requires a gcc version not older than gcc-5'. 

The README file also refers to a pre-complied binary (ASElux) that is should be available with the repo, but it is not in any of the folders provided. Would it be possible to upload this?

Many Thanks.

**Comment by Dazcam** [comment]
I managed to get this installed using gcc version 5.5. So the compiler needs to be > 5 to compile the ASElux binary and to run it.

**Comment by abl0719** [comment]
Hi Dazcam, thanks for the suggestion and I'm glad that you figured this out. By the way, the pre-compiled binary file is in the release tab.
![Annotation 2020-05-20 132201](https://user-images.githubusercontent.com/9859412/82493552-030dcb00-9a9d-11ea-9836-738938bb51d5.png)
