### ISSUE TITLE
Issue is ASElux align

### ISSUE THREAD

**Issue by Dazcam** [abl0719/ASElux#19]
Hello,

I'm trying to run ASElux align. The process ran, and completed without any error messages. However, only one empty output file was generated.

The standard output was as follows:

```bash
loading index: /refs/ASEref
Building dynamic index... 
Start alignment... 
read reading went wrong..
read reading went wrong..
read reading went wrong..
read reading went wrong..
read reading went wrong..
read reading went wrong..
read reading went wrong..
read reading went wrong..
read reading went wrong..
Processed 374140 reads
average speed is: 187070reads/s
read reading went wrong..
read reading went wrong..
read reading went wrong..
read reading went wrong..
read reading went wrong..
read reading went wrong..
read reading went wrong..
read reading went wrong..
read reading went wrong..
Processed 373872 reads
average speed is: 186936reads/s
```

The script I used was:

```bash
module load compiler/gnu/5

FASTQ_FOLDER=fastq/
REF_FOLDER=refs/
SAMPLE=17221

ASElux align --fq --pe --readLen 75 --index ${REF_FOLDER}ASEref --vcf ${SAMPLE}.chr.vcf \
--seqFiles  ${FASTQ_FOLDER}17221_S58_L007_R1_001.fastq \
${FASTQ_FOLDER}17221_S58_L007_R2_001.fastq \
${FASTQ_FOLDER}17221_S58_L008_R1_001.fastq \
${FASTQ_FOLDER}17221_S58_L008_R2_001.fastq \
--nthread 8 \
--out ${SAMPLE}_ase
```
The `.vcf`:

```bash
##fileformat=VCFv4.2
##source=ASElux
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
chr1	794299	rs4951859	C	G	.	PASS	.	GT	0|0
chr1	817186	rs3094315	G	A	.	GENOTYPED	.	GT	0|0
chr1	817341	rs3131972	A	G	.	GENOTYPED	.	GT	0|0
chr1	818025	rs3115860	C	A	.	PASS	.	GT	0|0
chr1	818161	rs2073813	G	A	.	PASS	.	GT	1|1
chr1	818802	rs3131969	A	G	.	PASS	.	GT	0|0
chr1	818812	rs3131968	A	G	.	PASS	.	GT	0|0
```

Example of a (unzipped) `.fastq`:

```bash
17221_S58_L007_R1_001.fastq 
@K00267:20:HCWLGBBXX:7:1101:2879:1138 1:N:0:NGATGT
NACAGACATAGAAAAGTCCAAAAAATACTTTAACTAAATTTATTTCTGTAACTCCAGTCTCTTTATTACTATTTG
+
#AAFAFJJJJJJJJFJJJJFJJJFJJJJJJFJ<JJJJJJJJJFJFFJJJJJJ<JJFJJFJJJJJJAJJF7AFFJF
@K00267:20:HCWLGBBXX:7:1101:4645:1138 1:N:0:NGATGT
NGCAAGGAAACTGAGTGAGTCCTTTTGCCTACCAACCTCGAAACAGAATATAGCATATCACACAGCAAGAGACA
+
#AAFFFJJJJJJJFJJJJJFFJAJJJJJJJJJJJJJJJJJJFFJFJFJFJJJJJJJJJJJJJJJJJJJJJJJJJ
@K00267:20:HCWLGBBXX:7:1101:10186:1138 1:N:0:NGATGT
NCGGTGCTCCTTCCTGTATCTCTCTCCTGACTTTTGTAAAGCAAGCACACTTCTGGGCTAGAAGCACAATGGAAGG
```

Files used for the static index build (also used the perl one-liner mentioned #5  to match chromosome IDs across these files and VCF):

```bash
# Reference genome 
`wget https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/latest/hg38.fa.gz`

# Gene annotations
`wget ftp://ftp.ensembl.org:21/pub/release-100/gtf/homo_sapiens/Homo_sapiens.GRCh38.100.gtf.gz'
```

I also tried running this script with only the first two fastqs (as well as running it serially), but got the same error. Can ASElux handle multiple paired end fastqs sequenced over several lanes? I have 4 for this sample but for a few others I have 12!

Any ideas on how to overcome this would be greatly appreciated.

Many Thanks.

**Comment by abl0719** [comment]
Hi, ASElux is able to handle multiple fastq files. The error message indicates that your read 1 and read 2 can not be matched. Do you mind to share a slice of your paired read files to check if there are any issues?

**Comment by Dazcam** [comment]
Thanks for responding so quickly. I have posted a 2M read subset for each of the 4 fastq files I used above [here](https://www.dropbox.com/sh/jg5ez9kdlzckfux/AAAQb4ZrZuShwLskEOjPHjwDa?dl=0). If you have any issues obtaining these files, or would prefer them shared in another way, please let me know.

Many thanks for taking the time to look into this for me.

**Comment by Dazcam** [comment]
Hello again,

Just to follow up on this, I'm not sure the fastqs are the problem, could you elaborate on that point a bit? 

The fastqs I'm using for this analysis have been used for a previous eQTL analysis. For those particular fastq files I sent they were previously aligned using Hisat2 and achieved an alignment rate of 91.46%. I've also tried fastqs from several different samples now, as well as using different annotation files for the indexing, but get the same error.

It would be useful to know if you have managed to replicate this error at your end. If you have managed to get it running with these fastqs, would it be possible to share the links for the reference/annotation files that you used to build the static index?

Many Thanks.

**Comment by Dazcam** [comment]
Finally got to the bottom of this - the **read lengths** in the fastqs didn't match. I set a hard cut off of 70 for each read across all files and the program ran. Closing this issue now, but I also had issues trying to create static index files using UCSC genome/annotation files. These are mentioned in comment appended to issue #20 . 

Many Thanks
