### ISSUE TITLE
F1 hybrid reads overlapping multiple SNPs?

### ISSUE THREAD

**Issue by petercombs** [abl0719/ASElux#3]
I'm interested in using ASElux for looking at allele-specific expression in F1 hybrids, where it's fairly straightforward to phase the SNPs to the parental genome.  In contrast, it seems like ASElux was designed for looking at unphased data, where two SNPs on a given read could be both REF, both ALT, or one REF and one ALT.  

Do you have any advice on best practices for quantifying gene-level allelic bias? My SNPs are relatively dense (on average, every 30bp or so, with 100bp reads), so I'm concerned that if I just sum the REF counts and ALT counts for all of the SNPs in a gene, I'll be double counting a lot.  

Thanks!

**Comment by abl0719** [comment]
Thank you for your interest! We are planning on a new version of ASElux that can utilize the phased genotype information. In the meanwhile, our latest update enables ASElux to count the reads once but not multiple times when there are multiple SNPs in a read. Using the new feature, you should be able to sum the REF and ALT counts for all SNPs in a gene without an issue.
