### ISSUE TITLE
Seg Fault at loading index (hg38)

### ISSUE THREAD

**Issue by nickgarza** [abl0719/ASElux#5]
Hi!
This may be a trivial issue, but I am having problems building the static index using hg38 as a base:
`../ASElux/bin/ASElux build --gtf hg38.gtf --ref hg38.fa --out ase-run`
`Building static index...`
`Segmentation fault (core dumped)`
The data in hg38.fa formatted as: 
>chr1
NNNNNNNNNNNNNN
NNNNNNNNNNNNNN

And the data in hg38.gtf:
`chr1    hg38_refGene    stop_codon      67093580        67093582        0.000000        -       .       gene_id "NM_001276352"; transcript_id "NM_001276352";`

Both were downloaded from UCSC Genome Browser.
Any assistance from anyone who has done this before would be appreciated!

**Comment by nickgarza** [comment]
After trying a different annotation, I get the following messages:
`Building static index...
Anootation finished...
annotation created...
ASElux: src/SuffixArray.cpp:358: int sais_main(const void*, int*, int, int, int, int, int): Assertion `(0 <= fs) && (0 < n) && (1 <= k)' failed.`

**Comment by abl0719** [comment]
Hi nickgarza,
ASElux requires the gtf file to have "gene", "transcript", and "exon" to build the static index. I assume that your first annotation file did not have that. As for the new issue, could you please let know what annotation file did you use? It seems that the chromosome name in the annotation file and the fasta file didn't match with each other.

Thanks,

**Comment by nickgarza** [comment]
Hello!
Thank you for the quick response. For my first attempt, I had retrieved my fasta file from http://hgdownload.cse.ucsc.edu/goldenPath/hg38/bigZips/ and my .gtf generated from http://genome.ucsc.edu/cgi-bin/hgTables with options:
Clade : Mammal
Genome : Human
Assembly : latest one (Currently GRCh38/hg38)
Group : Genes and Gene Predictions
Track : RefSeq Gene
Table : refGene
region : Check genome
Output fromat : GTF - gene transfer format
Output file : hg38.gtf

On my second attempt I used the same fasta, but the Homo_sapiens.GRCh38.87.gtf annotation.
If you have/know of a working hg38 fasta and corresponding gtf annotation that build the static index correctly that would be great!

**Comment by abl0719** [comment]
Hi

I believe that the chromosome name in Homo_sapiens.GRCh38.87.gtf is just number. However, the chromosome name in the fasta file has a "chr" in front. Thus, ASElux cannot match the reference genome and the annotation. Use a simple oneliner `perl -ne 'if (/^#/){print $_;}else{print "chr".$_;}' Homo_sapiens.GRCh38.87.gtf > Homo_sapiens.GRCh38.87.chr.gtf` should solve your issue by adding the "chr" to the annotation file.

Thanks,

**Comment by nickgarza** [comment]
Thank you! This resolved my static index build. It seems the problem was having the correct corresponding gtf in the right format. I am having trouble in the alignment process and will open a different thread to discuss.
