### ISSUE TITLE
Building dynamic index (Can not find any SNPs)

### ISSUE THREAD

**Issue by nickgarza** [abl0719/ASElux#6]
Hello!
When building my dynamic index with command:
`$ASElux align --fq --se --readLen 75 --index Z99-run --vcf Z99.vcf --seqFiles poolC_index10_all.fastq --out Z99-run_rc.txt`

I receive the following output: 
`Building static index...  
Anootation finished...  
annotation created...  
loading index: Z99-run  
Building dynamic index...   
Can not find any SNPs.
`
After checking in DynamicIndex.cpp I had seen that this exit statement is for cases where m_hetro_SNPs (line 69) is empty, however the .fastq and .vcf files are non-empty.
Consulting with fastqc, the .fastq is well formatted with average read length of 75 and the .vcf file has column entries for
`#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  sample`
Do you know of any other reasons for this error?
Thanks,

**Comment by abl0719** [comment]
Hi,

Could you please double check if the chromosome names in the vcf file are the same as your annotation? For example, If the vcf file uses 1 instead of chr1, ASElux won't identify the SNPs. Also, ASElux use the GT filed to identify heterozygous SNPs, do you have "0/1", "0|1", or "1|0" in the GT filed to mark the heterozygous SNPs?

Thanks,

**Comment by nickgarza** [comment]
Thank you! It seems my issue was the vcf using '#' instead of 'chr#', and using your command from Issue #5 readjusted the vcf so that everything was properly formatted! Thank you for all of your assistance.
--Nick

**Comment by nickgarza** [comment]
One comment--the SNP IDs in my index_rc.txt file came out as #:#########. I was confused as to how to interpret these IDs or if there was some error.

**Comment by abl0719** [comment]
This is a little wired. ASElux uses the same SNP id in vcf as in the output file. Do you mind to share a small piece of your vcf file and the output _rc.txt file?

**Comment by nickgarza** [comment]
Ah I see, the output of the _rc.txt file matches the peculiar ID from the vcf file in what appears to be (chr#):(loci/base position). Thank you for the suggestion! Just a quick conversion to rs# should do the trick for me.
