### ISSUE TITLE
error: Building dynamic index...  Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by sorrowripple** [abl0719/ASElux#7]
Hi, 
when I ran the command:
`ASElux align --fq --pe --readLen 150 --index ../../../p1.early-embryo_srb/0.ref/1.snp_annotation/3.ASElux_snp/1.C57BL6J/index/NCBIM37 --vcf ../../../p1.early-embryo_srb/0.ref/1.snp_annotation/3.ASElux_snp/1.C57BL6J/test.snp --seqFiles ../1.test_data/test_1.fq ../1.test_data/test_2.fq --out test`

the output was:
'loading index: ../../../p1.early-embryo_srb/0.ref/1.snp_annotation/3.ASElux_snp/1.C57BL6J/index/NCBIM37
Building dynamic index... 
Segmentation fault (core dumped)
'
the .gtf file was downloaded from GENCODE(ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M1/gencode.vM1.annotation.gtf.gz), The chromsome names were all "chr#".
Do you know the reasons for this error?
the demo files run fine.

**Comment by abl0719** [comment]
Thank you for the feedback. Do you mind to share a small piece of your vcf file so that I can check what causes the problem?

**Comment by orionzhou** [comment]
I got exactly the same error: /var/spool/torque/mom_priv/jobs/14516325.mesabim3.msi.umn.edu.SC: line 15: 15318 Segmentation fault      (core dumped) ASElux align --fq --pe --readLen 51 --count_once --
index aselux/db --vcf aselux/test.vcf --seqFiles 15_trim/BR025_a_1.fq.gz 15_trim/BR025_a_2.fq.gz --out BR025

I'm really only having ~30 SNPs in the vcf:

> #CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  mo17
> B01     21950   B01_21950       G       A       .       .       .       GT      0|1
> B01     24900   B01_24900       T       C       .       .       .       GT      0|1
> B01     26291   B01_26291       T       C       .       .       .       GT      0|1
> B01     27496   B01_27496       A       G       .       .       .       GT      0|1
> B01     27534   B01_27534       A       G       .       .       .       GT      0|1
> B01     27644   B01_27644       A       G       .       .       .       GT      0|1
> B01     27773   B01_27773       A       G       .       .       .       GT      0|1
> B01     28483   B01_28483       A       G       .       .       .       GT      0|1
> B01     28687   B01_28687       A       G       .       .       .       GT      0|1
> B01     28701   B01_28701       A       G       .       .       .       GT      0|1
> B01     29106   B01_29106       A       G       .       .       .       GT      0|1
> B01     29829   B01_29829       T       C       .       .       .       GT      0|1
> B01     30164   B01_30164       A       G       .       .       .       GT      0|1
> B01     30261   B01_30261       G       A       .       .       .       GT      0|1
> B01     31213   B01_31213       T       C       .       .       .       GT      0|1
> B01     31274   B01_31274       A       G       .       .       .       GT      0|1
> B01     31421   B01_31421       T       C       .       .       .       GT      0|1
> B01     32221   B01_32221       G       A       .       .       .       GT      0|1
> B01     32433   B01_32433       T       C       .       .       .       GT      0|1
> B01     32541   B01_32541       A       G       .       .       .       GT      0|1
> B01     32608   B01_32608       C       G       .       .       .       GT      0|1
> B01     32831   B01_32831       T       C       .       .       .       GT      0|1
> B01     33879   B01_33879       C       T       .       .       .       GT      0|1
> B01     36121   B01_36121       A       C       .       .       .       GT      0|1
> B01     36653   B01_36653       T       C       .       .       .       GT      0|1
> B01     36863   B01_36863       T       C       .       .       .       GT      0|1
> B01     36884   B01_36884       A       C       .       .       .       GT      0|1
> B01     37176   B01_37176       A       T       .       .       .       GT      0|1
> B01     38391   B01_38391       T       C       .       .       .       GT      0|1
> B01     38418   B01_38418       T       C       .       .       .       GT      0|1
> B01     39119   B01_39119       T       C       .       .       .       GT      0|1
> B01     39798   B01_39798       T       C       .       .       .       GT      0|1
> B01     41400   B01_41400       T       C       .       .       .       GT      0|1
> B01     41714   B01_41714       T       C       .       .       .       GT      0|1
> B01     41929   B01_41929       A       G       .       .       .       GT      0|1
> B01     42377   B01_42377       G       A       .       .       .       GT      0|1
> B01     43492   B01_43492       T       G       .       .       .       GT      0|1
> B01     43599   B01_43599       A       G       .       .       .       GT      0|1
> B01     45511   B01_45511       T       A       .       .       .       GT      0|1
> B01     46044   B01_46044       A       G       .       .       .       GT      0|1
> B01     46746   B01_46746       A       G       .       .       .       GT      0|1
> B01     46912   B01_46912       A       G       .       .       .       GT      0|1
> B01     48140   B01_48140       C       T       .       .       .       GT      0|1
> B01     49527   B01_49527       A       G       .       .       .       GT      0|1
> B01     49847   B01_49847       C       T       .       .       .       GT      0|1
> B01     50744   B01_50744       T       C       .       .       .       GT      0|1
> B01     50812   B01_50812       A       G       .       .       .       GT      0|1
> B01     52192   B01_52192       T       A       .       .       .       GT      0|1

I've also tried including only first 5 of the SNPs and it complains "Cannot find any SNP".

Any idea what's going on?

**Comment by duzc-Repos** [comment]
> Thank you for the feedback. Do you mind to share a small piece of your vcf file so that I can check what causes the problem?

Sorry, I missed this massage.
the <*.vcf> was download from ftp://ftp-mouse.sanger.ac.uk/REL-1211-SNPs_Indels/mgp.v2.snps.annot.reformat.vcf.gz, and after some processing, it become sth as following:
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	smaple
chr1	3000248	1:3000248:rs32640266	G	T	.	.	.	GT	0/1
chr1	3000289	1:3000289:rs32137367	T	G	.	.	.	GT	0/1
chr1	3000353	1:3000353:rs31719101	C	T	.	.	.	GT	0/1
chr1	3000355	1:3000355:rs31443144	T	C	.	.	.	GT	0/1
chr1	3000444	1:3000444:rs32793820	T	A	.	.	.	GT	0/1
chr1	3000906	1:3000906:.	G	T	.	.	.	GT	0/1
chr1	3001066	1:3001066:rs49746803	G	T	.	.	.	GT	0/1
chr1	3001111	1:3001111:rs46544544	G	C	.	.	.	GT	0/1
chr1	3001183	1:3001183:rs46345706	C	T	.	.	.	GT	0/1

**Comment by duzc-Repos** [comment]
> I got exactly the same error: /var/spool/torque/mom_priv/jobs/14516325.mesabim3.msi.umn.edu.SC: line 15: 15318 Segmentation fault (core dumped) ASElux align --fq --pe --readLen 51 --count_once --
> index aselux/db --vcf aselux/test.vcf --seqFiles 15_trim/BR025_a_1.fq.gz 15_trim/BR025_a_2.fq.gz --out BR025
> 
> I'm really only having ~30 SNPs in the vcf:
> 
> > #CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  mo17
> > B01     21950   B01_21950       G       A       .       .       .       GT      0|1
> > B01     24900   B01_24900       T       C       .       .       .       GT      0|1
> > B01     26291   B01_26291       T       C       .       .       .       GT      0|1
> > B01     27496   B01_27496       A       G       .       .       .       GT      0|1
> > B01     27534   B01_27534       A       G       .       .       .       GT      0|1
> > B01     27644   B01_27644       A       G       .       .       .       GT      0|1
> > B01     27773   B01_27773       A       G       .       .       .       GT      0|1
> > B01     28483   B01_28483       A       G       .       .       .       GT      0|1
> > B01     28687   B01_28687       A       G       .       .       .       GT      0|1
> > B01     28701   B01_28701       A       G       .       .       .       GT      0|1
> > B01     29106   B01_29106       A       G       .       .       .       GT      0|1
> > B01     29829   B01_29829       T       C       .       .       .       GT      0|1
> > B01     30164   B01_30164       A       G       .       .       .       GT      0|1
> > B01     30261   B01_30261       G       A       .       .       .       GT      0|1
> > B01     31213   B01_31213       T       C       .       .       .       GT      0|1
> > B01     31274   B01_31274       A       G       .       .       .       GT      0|1
> > B01     31421   B01_31421       T       C       .       .       .       GT      0|1
> > B01     32221   B01_32221       G       A       .       .       .       GT      0|1
> > B01     32433   B01_32433       T       C       .       .       .       GT      0|1
> > B01     32541   B01_32541       A       G       .       .       .       GT      0|1
> > B01     32608   B01_32608       C       G       .       .       .       GT      0|1
> > B01     32831   B01_32831       T       C       .       .       .       GT      0|1
> > B01     33879   B01_33879       C       T       .       .       .       GT      0|1
> > B01     36121   B01_36121       A       C       .       .       .       GT      0|1
> > B01     36653   B01_36653       T       C       .       .       .       GT      0|1
> > B01     36863   B01_36863       T       C       .       .       .       GT      0|1
> > B01     36884   B01_36884       A       C       .       .       .       GT      0|1
> > B01     37176   B01_37176       A       T       .       .       .       GT      0|1
> > B01     38391   B01_38391       T       C       .       .       .       GT      0|1
> > B01     38418   B01_38418       T       C       .       .       .       GT      0|1
> > B01     39119   B01_39119       T       C       .       .       .       GT      0|1
> > B01     39798   B01_39798       T       C       .       .       .       GT      0|1
> > B01     41400   B01_41400       T       C       .       .       .       GT      0|1
> > B01     41714   B01_41714       T       C       .       .       .       GT      0|1
> > B01     41929   B01_41929       A       G       .       .       .       GT      0|1
> > B01     42377   B01_42377       G       A       .       .       .       GT      0|1
> > B01     43492   B01_43492       T       G       .       .       .       GT      0|1
> > B01     43599   B01_43599       A       G       .       .       .       GT      0|1
> > B01     45511   B01_45511       T       A       .       .       .       GT      0|1
> > B01     46044   B01_46044       A       G       .       .       .       GT      0|1
> > B01     46746   B01_46746       A       G       .       .       .       GT      0|1
> > B01     46912   B01_46912       A       G       .       .       .       GT      0|1
> > B01     48140   B01_48140       C       T       .       .       .       GT      0|1
> > B01     49527   B01_49527       A       G       .       .       .       GT      0|1
> > B01     49847   B01_49847       C       T       .       .       .       GT      0|1
> > B01     50744   B01_50744       T       C       .       .       .       GT      0|1
> > B01     50812   B01_50812       A       G       .       .       .       GT      0|1
> > B01     52192   B01_52192       T       A       .       .       .       GT      0|1
> 
> I've also tried including only first 5 of the SNPs and it complains "Cannot find any SNP".
> 
> Any idea what's going on?

Maybe "|" should be replaced by "/", i'm not sure .

**Comment by abl0719** [comment]
Thank you for the information. '|' or '\' should both work. I'll check and this and get back to you soon.

**Comment by abl0719** [comment]
Hi @duzc19940423, sorry for the delay. If you do not have any homozygous SNP in the vcf file. This error might occur. So when you process the vcf file, please keep the homozygous ones.

**Comment by duzc-Repos** [comment]
> Hi @duzc19940423, sorry for the delay. If you do not have any homozygous SNP in the vcf file. This error might occur. So when you process the vcf file, please keep the homozygous ones.

Thank you! I'll try it.
