### ISSUE TITLE
Is there a limit to number of SNPs in VCF file?

### ISSUE THREAD

**Issue by ilakya-selvarajan** [abl0719/ASElux#8]
Hi!
1. My problem is with the VCF file where I don't know the genotypes of the SNPs. So, as a test run I tried every SNP as heterozygous. Attaching the VCF file here.  
2. When I tried run for all the SNPs, there was Segmentation fault (core dumped) error but when I try about 20 SNPs it runs with Can not find any SNPs.
3. The static index build was successful without errors, and all the chromosome annotations are in the same way (chrN)

Can you please look at my VCF file?
[SNP_test.txt](https://github.com/abl0719/ASElux/files/2741313/SNP_test.txt)

Thanks!

**Comment by abl0719** [comment]
Hi,

ASElux is aimed to detect the allele-specific expression in the exons. Thus, only the SNPs that are in the exonic region are taken into account. Can you please try some SNPs in the exonic region and see if that works?

As for your first question, I highly recommend using ASElux only when you have the personal genotype information. Treating all SNPs as heterozygous may require too much memory and lead to a failure.

Best,
Zong
