### ISSUE TITLE
ASElux build chokes on a valid fasta file

### ISSUE THREAD

**Issue by jdidion** [abl0719/ASElux#9]
I try to use this reference: ftp://ftp-trace.ncbi.nih.gov/1000genomes/ftp/technical/reference/human_g1k_v37.fasta.gz

I get the following error: `ASElux: src/SuffixArray.cpp:358: int sais_main(const void*, int*, int, int, int, int, int): Assertion `(0 <= fs) && (0 < n) && (1 <= k)' failed.`

When I remove the everything after the chromosome names in the contig names, it works. Looks like the fasta parser needs to be updated to ignore everything including and after the first space in contig names.

**Comment by abl0719** [comment]
Thanks for the feedback. The updated version addressed this issue.
